### ISSUE TITLE
serializeToJsonString uses " ," for separator instead of "," for array values

### ISSUE THREAD

**Issue by PierrickVoulet** [haberman/protobuf#2]
**What version of protobuf and what language are you using?**
Version: php-upb-msg (protobuf2)
Language: PHP

**What operating system (Linux, Windows, ...) and version?**
Linux 5.2.17-1rodete3-amd64 x86_64

**What runtime / compiler are you using (e.g., python version or gcc version)**
PHP Extension (C implementation)

**What did you do?**
Run the following script (some proto messages are defined [here](https://github.com/googleapis/googleapis/tree/master/google/ads/googleads/v3)):

```php
<?php
$array = new \Google\Ads\GoogleAds\V3\Services\SearchGoogleAdsResponse([
    'results' => [
        new \Google\Ads\GoogleAds\V3\Services\GoogleAdsRow([
            'campaign' => new \Google\Ads\GoogleAds\V3\Resources\Campaign([
                'id' => new \Google\Protobuf\Int64Value(['value' => 1])
            ])
        ]),
        new \Google\Ads\GoogleAds\V3\Services\GoogleAdsRow([
            'campaign' => new \Google\Ads\GoogleAds\V3\Resources\Campaign([
                'id' => new \Google\Protobuf\Int64Value(['value' => 1])
            ])
        ])
    ]
]);
print $array->serializeToJsonString();
```

**What did you expect to see**
`{"results":[{"campaign":{"id":"1"}},{"campaign":{"id":"1"}}]}`

**What did you see instead?**
`{"results":[{"campaign":{"id":"1"}}, {"campaign":{"id":"1"}}]}`

**Anything else we should know about your project / environment**
Removing the extra space on [this line](https://github.com/haberman/protobuf/blob/php-upb-msg/php/ext/google/protobuf2/php-upb.c#L7920) fixed the issue on my side.

**Comment by haberman** [comment]
This should be fixed in https://github.com/haberman/protobuf/commit/50314698bb7eaa2121d9ef96b8f6feb0fa80bd8b. Please re-open if you run into it again.

**Comment by PierrickVoulet** [comment]
Verified
