### ISSUE TITLE
serializeToJsonString prints the wrong enum value name 

### ISSUE THREAD

**Issue by PierrickVoulet** [haberman/protobuf#3]
**What version of protobuf and what language are you using?**
Version: php-upb-msg (protobuf2)
Language: PHP

**What operating system (Linux, Windows, ...) and version?**
Linux 5.2.17-1rodete3-amd64 x86_64

**What runtime / compiler are you using (e.g., python version or gcc version)**
PHP Extension (C implementation)

**What did you do?**
Run the following script (some proto messages are defined [here](https://github.com/googleapis/googleapis/tree/master/google/ads/googleads/v3)):

```php
<?php
$errorCode = new \Google\Ads\GoogleAds\V3\Errors\ErrorCode([
    'authentication_error' => \Google\Ads\GoogleAds\V3\Errors\AuthenticationErrorEnum\AuthenticationError::AUTHENTICATION_ERROR
]);
```

**What did you expect to see**
`{"authenticationError":"AUTHENTICATION_ERROR"}`

**What did you see instead?**
`{"authenticationError":"UNSPECIFIED"}`

**Anything else we should know about your project / environment**
None.

**Comment by haberman** [comment]
I am having trouble reproducing this. I tried creating the same setup in the protobuf unit tests but the JSON output was as expected: https://github.com/haberman/protobuf/commit/eeab3d13a52293423413dcf43ea5e37966381d32

Can you give me a full setup to reproduce this, or add a test to the protobuf test suite that reproduces it?

**Comment by haberman** [comment]
Thanks for the repro! This turned out to be a deep bug in upb's data representation layer. Oneof cases were getting stored at the wrong offset (one byte off) and overwriting the first byte of the enum data.

This should be fixed in https://github.com/haberman/protobuf/commit/b15ccb0bc3c89ca0ae1853b0f139f8c9b65e4fd6

**Comment by PierrickVoulet** [comment]
Verified
