### ISSUE TITLE
serializeToString fails printing an instance of LRO

### ISSUE THREAD

**Issue by PierrickVoulet** [haberman/protobuf#4]
**What version of protobuf and what language are you using?**
Version: php-upb-msg (protobuf2)
Language: PHP

**What operating system (Linux, Windows, ...) and version?**
Linux 5.2.17-1rodete3-amd64 x86_64

**What runtime / compiler are you using (e.g., python version or gcc version)**
PHP Extension (C implementation)

**What did you do?**
Run the following script (some proto messages are defined [here](https://github.com/googleapis/googleapis/tree/master/google/longrunning)):

```php
<?php
$response = new \Google\Protobuf\GPBEmpty();
$any = new \Google\Protobuf\Any();
$any->setValue($response->serializeToString());
$lro = new \Google\LongRunning\Operation();
$lro->setResponse($any);
print $lro->serializeToString();
```

**What did you expect to see**
No PHP Fatal error.

**What did you see instead?**
`PHP Fatal error:  Uncaught Exception: Error occurred during serialization`

**Anything else we should know about your project / environment**
None.

**Comment by haberman** [comment]
I'm having trouble reproducing this error. I tried creating the same pattern in https://github.com/haberman/protobuf/commit/116ebc45b0141d46edebf6973e8b86c95405f5c8 but this didn't throw any error.

I can trigger an error though if I change it to `serializeToJSONString()`. I added better reporting of JSON serialization errors in https://github.com/haberman/protobuf/commit/b0d4ef0f9e30cea7b931a841b111e6876b1e04c2 and I got:

```
Exception: Error occurred during JSON serialization: Bad type URL
```

It's true that the `Any` message in this case doesn't seem to have a type URL. But it should serialize fine if you are serializing to binary format.

If you are indeed serializing to binary format, I wonder if you could help me reproduce this in the protobuf tests?

**Comment by PierrickVoulet** [comment]
I gave it another try with the latest changes: it is now fixed and verified.
