### ISSUE TITLE
mergeFromJsonString fails with `Error occurred during parsing` error

### ISSUE THREAD

**Issue by PierrickVoulet** [haberman/protobuf#7]
**What version of protobuf and what language are you using?**
Version: php-upb-msg (protobuf2)
Language: PHP

**What operating system (Linux, Windows, ...) and version?**
Linux 5.2.17-1rodete3-amd64 x86_64

**What runtime / compiler are you using (e.g., python version or gcc version)**
PHP Extension (C implementation)

**What did you do?**
Loaded this [json content](https://github.com/googleads/google-ads-php/blob/master/src/Google/Ads/GoogleAds/Util/Testing/testdata/test_cases.json) into a [TestSuite](https://github.com/googleads/google-ads-php/blob/master/src/Google/Ads/GoogleAds/Util/Testing/proto/Google/Ads/GoogleAds/Util/Testing/tester.proto#L13) message instance  at runtime using the following script:

```php
<?php
$testSuite = new TestSuite();
$testSuite->mergeFromJsonString($filepath);
print $testSuite->getTestCases()->count() . PHP_EOL;
```

**What did you expect to see**
> 9

**What did you see instead?**
`PHP Fatal error:  Uncaught Exception: Error occurred during parsing: Expected string`

**Anything else we should know about your project / environment**
None.

**Comment by haberman** [comment]
I tracked this down to the following fragment:

```
"expected_mask": {}
```

Here `expected_mask` is a `FieldMask`. The new parser expects this to be a string. I guess the old parser was lenient and accepted an empty object here.

What generated this payload? Can it be fixed to serialize an empty FieldMask as `""`? Or do we need to change the new parser to accept this? (ideally behind some compatibility flag that we can eventually remove).

**Comment by haberman** [comment]
btw. I need to add line/col info to the error output so this is easier to diagnose!

**Comment by PierrickVoulet** [comment]
> I tracked this down to the following fragment:
> 
> ```
> "expected_mask": {}
> ```
> 
> Here `expected_mask` is a `FieldMask`. The new parser expects this to be a string. I guess the old parser was lenient and accepted an empty object here.
> 
> What generated this payload? Can it be fixed to serialize an empty FieldMask as `""`? Or do we need to change the new parser to accept this? (ideally behind some compatibility flag that we can eventually remove).

Good catch. I tried with empty string but it now fails because of the snake case being used for field names throughout the file content. This seems to be an issue on our side, I will continue digging this.

**Comment by PierrickVoulet** [comment]
Verified
